# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 449)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
"  border: none;\n"
"  background-color: transparent;\n"
"  color: #FFF; /* Specify a default color */\n"
"}\n"
"\n"
"#centralwidget {\n"
"  background-color: white\n"
";\n"
"}\n"
"\n"
"#side_menu {\n"
"  background-color: #071e26;\n"
"  border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  padding: 10px;\n"
"  background-color: #071e26;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"#main_body {\n"
"  background-color: #071e26;\n"
"  border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons_folder/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.header)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QWidget(self.frame_2)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.side_menu)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/New folder/airplay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/New folder/award.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/New folder/coffee.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/New folder/music.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/New folder/wifi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.verticalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_body = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setStyleSheet("\n"
"color:white;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"\n"
"")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.main_body)
        self.label_2.setMaximumSize(QtCore.QSize(200, 22))
        self.label_2.setStyleSheet("color: white;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:25px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.main_body)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(200, 22))
        self.label_3.setStyleSheet("color: white;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:25px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.main_body)
        self.label_4.setMaximumSize(QtCore.QSize(200, 22))
        self.label_4.setStyleSheet("color: white;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:25px;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.main_body)
        self.label_5.setMaximumSize(QtCore.QSize(200, 22))
        self.label_5.setStyleSheet("color: white;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:25px;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.main_body)
        self.label_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_6.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
"font-size:30px;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.main_body)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setStyleSheet("font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.pushButton_7 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_7.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_8.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.main_body)
        self.label_20.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_20.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
"font-size:30px;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.main_body)
        self.label_21.setMinimumSize(QtCore.QSize(120, 0))
        self.label_21.setStyleSheet("font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.pushButton_21 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_21.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_12.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_22.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_12.addWidget(self.pushButton_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_22 = QtWidgets.QLabel(self.main_body)
        self.label_22.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_22.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
"font-size:30px;")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.main_body)
        self.label_23.setMinimumSize(QtCore.QSize(120, 0))
        self.label_23.setStyleSheet("font-size:30px;\n"
"font-family: \"Times New Roman\", Times, serif;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.pushButton_23 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_23.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_13.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_24.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_13.addWidget(self.pushButton_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_24 = QtWidgets.QLabel(self.main_body)
        self.label_24.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_24.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.main_body)
        self.label_25.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        self.pushButton_25 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_25.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_14.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_26.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_14.addWidget(self.pushButton_26)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_26 = QtWidgets.QLabel(self.main_body)
        self.label_26.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_26.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
"font-size:30px;")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.main_body)
        self.label_27.setMinimumSize(QtCore.QSize(120, 0))
        self.label_27.setStyleSheet("font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.pushButton_27 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_27.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_15.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.main_body)
        self.pushButton_28.setStyleSheet("background-color: Transparent;\n"
"color: white;\n"
" border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"font-family: \"Times New Roman\", Times, serif;\n"
"font-size:30px;")
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_15.addWidget(self.pushButton_28)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout.addWidget(self.main_body)
        self.main_body.raise_()
        self.side_menu.raise_()
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.menu_expanded = False

        # Connect the button click event to the toggle_menu function
        self.pushButton.clicked.connect(self.toggle_menu)

        # Set up the animation for the side menu
        self.side_menu_animation = QtCore.QPropertyAnimation(self.side_menu, b"maximumWidth")
        self.side_menu_animation.setDuration(300)

        # Set up the central widget animation for overlay effect
        self.central_widget_animation = QtCore.QPropertyAnimation(self.centralwidget, b"geometry")
        self.central_widget_animation.setDuration(300)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def toggle_menu(self):
        # Toggle the menu state
        self.menu_expanded = not self.menu_expanded

        # Define the target width for the side menu
        target_width = 200 if self.menu_expanded else 0

        # Update the side menu animation
        self.side_menu_animation.setEndValue(target_width)
        self.side_menu_animation.start()

        # Update the central widget animation for overlay effect
        if self.menu_expanded:
            self.central_widget_animation.setEndValue(QtCore.QRect(200, 0, 586, 370))
        else:
            self.central_widget_animation.setEndValue(QtCore.QRect(0, 0, 586, 370))
        self.central_widget_animation.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "Samadhan App"))
        self.pushButton_2.setText(_translate("MainWindow", "Item 1"))
        self.pushButton_3.setText(_translate("MainWindow", "Item 2"))
        self.pushButton_4.setText(_translate("MainWindow", "Item 3"))
        self.pushButton_5.setText(_translate("MainWindow", "Item 4"))
        self.pushButton_6.setText(_translate("MainWindow", "Item 5"))
        self.pushButton_17.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_18.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_19.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.label_4.setText(_translate("MainWindow", "Academic Supervison"))
        self.label_5.setText(_translate("MainWindow", "Academic Anaysis"))
        self.label_7.setText(_translate("MainWindow", "     Time Effecient"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Menu"))
        self.pushButton.setMaximumHeight(58)
        self.label.setText(_translate("MainWindow", "My app"))
        self.pushButton_2.setText(_translate("MainWindow", "Item 1"))
        self.pushButton_3.setText(_translate("MainWindow", "Item 2"))
        self.pushButton_4.setText(_translate("MainWindow", "Item 3"))
        self.pushButton_5.setText(_translate("MainWindow", "Item 4"))
        self.pushButton_6.setText(_translate("MainWindow", "Item 5"))
        self.label_2.setText(_translate("MainWindow", "S.N"))
        self.label_3.setText(_translate("MainWindow", "Subject"))
        self.label_4.setText(_translate("MainWindow", "    Upload Note"))
        self.label_5.setText(_translate("MainWindow", "       View Note"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "Physics"))
        self.pushButton_7.setText(_translate("MainWindow", "    Upload Note"))
        self.pushButton_8.setText(_translate("MainWindow", "View Notes"))
        self.label_20.setText(_translate("MainWindow", "2"))
        self.label_21.setText(_translate("MainWindow", "Chemistry"))
        self.pushButton_21.setText(_translate("MainWindow", "    Upload Note"))
        self.pushButton_22.setText(_translate("MainWindow", "View Notes"))
        self.label_22.setText(_translate("MainWindow", "3"))
        self.label_23.setText(_translate("MainWindow", "Maths"))
        self.pushButton_23.setText(_translate("MainWindow", "    Upload Note"))
        self.pushButton_24.setText(_translate("MainWindow", "View Notes"))
        self.label_24.setText(_translate("MainWindow", "4"))
        self.label_25.setText(_translate("MainWindow", "Java"))
        self.pushButton_25.setText(_translate("MainWindow", "    Upload Note"))
        self.pushButton_26.setText(_translate("MainWindow", "View Notes"))
        self.label_26.setText(_translate("MainWindow", "5"))
        self.label_27.setText(_translate("MainWindow", "Python"))
        self.pushButton_27.setText(_translate("MainWindow", "    Upload Note"))
        self.pushButton_28.setText(_translate("MainWindow", "View Notes"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
